# Site settings
author: Sara Kantor
title: A Data Scientist's Adventures in Full Stack
header-img: img/home-bg.png
email: sara.kantor.nv@gmail.com
copyright_name: Sara Kantor
description: > # this means to ignore newlines until "baseurl:"
  What happens when you stick someone comfortable with pandas into Ruby?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Sara_Kantor
github_username:  skantor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
